version: '2.1'
services:
    postgres:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: ${DOCSERVER_POSTGRES_PW:-demo}
      volumes:
        - postgres-data:/var/lib/postgresql/data
    docserver:
        image: docserver:latest
        ports:
            - 8001:80
        environment:
          - DOCSERVER_DATABASE_URI=postgresql+psycopg2://postgres:${DOCSERVER_POSTGRES_PW:-demo}@postgres
          - DOCSERVER_SAFE_KEY=827c2c51-8413-4199-9606-6eab02d6f302
          - DOCSERVER_SALT=420979da-f8d2-4cb3-980b-b35bf3191d56
          # Pass through additional configuration variables here
          - DOCSERVER_AUTH_BACKEND
          - DOCSERVER_AUTH_ENABLED
          - DOCSERVER_AUTH_SECRET
          - DOCSERVER_AUTH_SALT
          - DOCSERVER_SESSION_SECRET
          - DOCSERVER_UPLOAD_TOKEN_SECRET
          - DOCSERVER_AAD_CLIENT_SECRET
          - DOCSERVER_HOST_NAME
          - DOCSERVER_AAD_CLIENT_ID
          - DOCSERVER_ADMIN_USERS
        depends_on:
          - postgres
volumes:
  postgres-data: